import './../blocks/big-card/big-card.js'
import './../blocks/good-card/good-card.js'
import './../blocks/main-slider/main-slider.js'
import './../blocks/banner/banner.js'
import './../blocks/subscribe/subscribe.js'
import './../blocks/billet/billet.js'
import './../blocks/button/button.js'
import './../blocks/path/path.js'
import './../blocks/big-card-wrapper/big-card-wrapper.js'
import './../blocks/cart-card/cart-card.js'
import './../blocks/cart-thumb/cart-thumb.js'
import './../blocks/cart-item/cart-item.js'
import './../blocks/quantity-input/quantity-input.js'
import './../blocks/filter/filter.js'
import './../blocks/checkbox/checkbox.js'
import './../blocks/category-main/category-main.js'
import './../blocks/footer-subscribe/footer-subscribe.js'
import './../blocks/footer-contacts/footer-contacts.js'
import './../blocks/footer-socials/footer-socials.js'


