import './../blocks/good-card/good-card.js'
import './../blocks/main-slider/main-slider.js'
import './../blocks/footer-subscribe/footer-subscribe.js'
import './../blocks/footer-contacts/footer-contacts.js'
import './../blocks/footer-socials/footer-socials.js'